version: "3.7"

services:

  db:
    image: "postgres"
    restart: "always"
    container_name: "better_commerce_db"
    env_file: ".env"
    ports:
      - "5433:5432"

networks:
  overlay:
    driver: 'bridge'